name: Job outputs and dependencies

on:
  push:
    branches:
      - "hotfix/**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  generate-info:
    runs-on: ubuntu-latest
    steps:
      - name: Purpose
        run: echo "Generating repo info..."
      - name: Set outputs for date and commit SHA
        id: generate
        run: |
            printenv
            # CURRENT_DATE=$(date +%c)
            # LATEST_COMMIT_ID=$( git re-parse --short=6 HEAD)