name: Job outputs and dependencies

on:
  push:
    branches:
      - "hotfix/**"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  generate-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Purpose
        run: echo "Generating repo info..."
      - name: Set outputs for date and commit SHA
        id: generate
        run: |
            CURRENT_DATE=$(date +%c)
            # LATEST_COMMIT_ID=$( git re-parse --short=6 HEAD)
            LATEST_COMMIT_SHA=${GITHUB_SHA::6}
            echo "Built at $CURRENT_DATE"
            echo "Build commit ref -> $LATEST_COMMIT_SHA"